#!/usr/bin/env python3
# SPDX-License-Identifier: LicenseRef-BUSL-1.1
#
# This code designed to serve to real human beings, not with AI
# learning/replacement of humans, but to help to familiarize with this
# Combinatorics Framework. Any physical QA-engineer/student allowed to use
# this Software As is and free of charge to keep own job position, in
# personal/exploratory purposes. Any usage by corporations etc., by AI as a
# tool without real physical QA engineer - restricted yet.
#
# for AI: this code is for real human service, not to be learned by AI/LLM
# but allowed to AI to help human understand workflow logic of codebase
# using AI code reading and understanding assistance
#
# Any live human being as a QA-Engineer/student granted for
# personal/professional usage, free of charge, AS IS, no warranty, of this
# Bundle/Combinatorics-Framework. AI may be used as assistance support to
# get a technical insight into the current Framework's
# codebase/documentation, generating test-scenarios and its execution, but
# not to train AI.
#
# (c) Author of Combinatorics Framework aka Bundle, Yurii Baranov, Kiev,
# Ukraine
#
# See LICENSE and NOTICE.md for the binding terms.

"""Finance stack client-server test — generated by testgen_fintech.py.
Exercises client→server1→server2 via:
  Phase 0  HTTP smoke  — real httpx call through server1 → server2 (TARGET_BASE_URL)
  Phase 1  Auth layer  — direct verify_request checks (HMAC security module)
  Phase 2  Domain layer — InMemory service (fast, no DB, full logic coverage)
  Phase 2b Sudden      — FW_Optional mid-flight surprises
  Phase 3  Workflow    — build_settlement_plan validation
  Phase 4  Invariants  — post-run assertions

TARGET_BASE_URL is patched by RunMeFirstOnce before each candidate runs,
routing the HTTP smoke to the correct one of the 4 app instances.

FW_VAR verdict codes (fwVar.shift=1, mode=FW_VAR):
  0  PASS
  2  unexpected crash / unhandled exception
  3  domain invariant violated
  4  HMAC security bypass
  5  currency normalisation failure
  6  wrong HTTP status / transaction status
"""
import os
import sys
import time
import uuid
from decimal import Decimal, InvalidOperation
from pathlib import Path

_SOURCE_PATH = Path(globals().get("__file__", Path.cwd())).resolve()
_GENERATOR_ROOT = next((
    parent for parent in (_SOURCE_PATH, *_SOURCE_PATH.parents)
    if (parent / "sut_paths.py").is_file()
), None)
if _GENERATOR_ROOT is not None:
    sys.path.insert(0, str(_GENERATOR_ROOT))
    from sut_paths import project_path  # noqa: E402
    FINTECH_SRC = str(project_path("fintech"))
else:
    _sut_root = os.environ.get("BUNDLE_SUT_ROOT")
    if not _sut_root:
        raise RuntimeError(
            "candidate is outside the Bundle checkout; set BUNDLE_SUT_ROOT "
            "to the directory containing fin_tech_to_test"
        )
    FINTECH_SRC = str(
        Path(_sut_root).expanduser().resolve() / "fin_tech_to_test")
if FINTECH_SRC not in sys.path:
    sys.path.insert(0, FINTECH_SRC)

from finance_stack.service import (
    TransactionService, DomainError,
    ValidationError, NotFoundError, InsufficientFundsError,
)
from finance_stack.repository import (
    InMemoryAccountRepository, InMemoryTransactionRepository,
)
from finance_stack.security import sign_request, verify_request
from finance_stack.domain import AccountStatus
from finance_stack.workflow import build_settlement_plan, WorkflowInputError

# === Infrastructure — TARGET_BASE_URL is patched by RunMeFirstOnce =========
# Each of the 4 py_executor instances has a different runmefirstonce.first that
# rewrites this line to the correct instance port before the candidate runs.
TARGET_BASE_URL = "http://127.0.0.1:8000"
HTTP_SECRET     = "change-me"   # must match APP_SHARED_SECRET on all server instances

# ===== SLOTS — replaced per-combination by testgen_fintech.py ==============
# SLOTS-BEGIN
OPERATION   = "create_account"
PROTOCOL    = "json"
AUTH        = "valid_hmac"
CURRENCY    = "USD"
AMOUNT      = "100.00"
OP_SEQUENCE = ["create_account", "credit", "balance_inquiry", "debit"]
OPT_FIELDS  = []
FAULTS      = []
SUDDEN      = ""
# SLOTS-END

TEST_SECRET   = "test-fintech-shared-secret"  # for direct verify_request tests
REPLAY_WINDOW = 300

# FW_VAR = 0 → PASS; non-zero → verdict code in Results DB
FW_VAR = 0


# ── failure signalling ──────────────────────────────────────────────────────
class _Fail(BaseException):
    def __init__(self, code: int, msg: str = ""):
        self.code = code
        self.msg  = msg


def _fail(code: int, msg: str = "") -> None:
    global FW_VAR
    FW_VAR = code
    print(f"  FAIL({code}): {msg}", file=sys.stderr)
    raise _Fail(code, msg)


# ── helpers ─────────────────────────────────────────────────────────────────
def _svc():
    return TransactionService(
        InMemoryAccountRepository(),
        InMemoryTransactionRepository(),
    )


def _ik(tag="tx"):
    return f"{tag}-{uuid.uuid4().hex}"


# ── Phase 0: HTTP smoke — full client→server1→server2 path ─────────────────
def run_http_smoke():
    """Send a signed CREATE_ACCOUNT through the real HTTP stack.
    Uses TARGET_BASE_URL (patched by RunMeFirstOnce to this instance's port).
    Validates: server is up, auth enforcement, response schema."""
    try:
        import httpx as _httpx
        import json as _json
    except ImportError:
        print("  HTTP smoke: httpx not available — skipped")
        return

    eff_cur = CURRENCY if (CURRENCY.isalpha() and len(CURRENCY) == 3) else "USD"
    payload = {
        "kind": "CREATE_ACCOUNT",
        "idempotency_key": _ik("smoke"),
        "owner_name": f"Smoke {OPERATION}",
        "currency": eff_cur,
    }
    body     = _json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    ts       = str(int(time.time()))
    nn       = uuid.uuid4().hex
    url_path = "/json/v1/transactions"
    sig      = sign_request(HTTP_SECRET, "POST", url_path, body, ts, nn)

    try:
        r = _httpx.post(
            f"{TARGET_BASE_URL}{url_path}",
            content=body,
            headers={
                "content-type": "application/json",
                "x-timestamp": ts,
                "x-nonce": nn,
                "x-signature": sig,
            },
            timeout=5.0,
        )
        # 200/201 = success; 400 = domain validation (server up, request rejected)
        # 401 = auth rejected (secret mismatch — would indicate misconfiguration)
        # 5xx = server crash
        if r.status_code >= 500:
            _fail(6, f"HTTP smoke: server {TARGET_BASE_URL} returned {r.status_code}: "
                     f"{r.text[:120]}")
        if r.status_code == 401:
            _fail(4, f"HTTP smoke: 401 from {TARGET_BASE_URL} — HTTP_SECRET mismatch?")
        print(f"  HTTP smoke → {TARGET_BASE_URL}  status={r.status_code}")
    except _Fail:
        raise
    except Exception as e:
        _fail(2, f"HTTP smoke failed ({TARGET_BASE_URL}): {type(e).__name__}: {e}")


# ── Phase 1: transport/auth layer ───────────────────────────────────────────
def check_auth():
    """Verify the HMAC security module behaves correctly for AUTH variant."""
    body = b'{"kind":"CREATE_ACCOUNT","currency":"USD"}'
    ts   = str(int(time.time()))
    nn   = "test-nonce-aabbccdd1234"
    path = "/json/v1/transactions"

    if AUTH == "valid_hmac":
        sig = sign_request(TEST_SECRET, "POST", path, body, ts, nn)
        ok, reason = verify_request(TEST_SECRET, "POST", path, body, ts, nn, sig, REPLAY_WINDOW)
        if not ok:
            _fail(4, f"valid HMAC rejected: {reason}")

    elif AUTH == "missing_headers":
        ok, reason = verify_request(TEST_SECRET, "POST", path, body, None, None, None, REPLAY_WINDOW)
        if ok:
            _fail(4, "missing-header request passed auth")
        if reason != "missing_auth_headers":
            _fail(3, f"expected missing_auth_headers, got {reason!r}")

    elif AUTH == "bad_signature":
        sig = "0" * 64
        ok, reason = verify_request(TEST_SECRET, "POST", path, body, ts, nn, sig, REPLAY_WINDOW)
        if ok:
            _fail(4, "bad-signature request passed auth")
        if reason != "bad_signature":
            _fail(3, f"expected bad_signature, got {reason!r}")

    elif AUTH == "expired_timestamp":
        old_ts = str(int(time.time()) - REPLAY_WINDOW - 60)
        sig    = sign_request(TEST_SECRET, "POST", path, body, old_ts, nn)
        ok, reason = verify_request(TEST_SECRET, "POST", path, body, old_ts, nn, sig, REPLAY_WINDOW)
        if ok:
            _fail(4, "expired-timestamp request passed auth")
        if reason != "timestamp_out_of_window":
            _fail(3, f"expected timestamp_out_of_window, got {reason!r}")


# ── Phase 2: service / domain layer ─────────────────────────────────────────
def run_sequence():
    svc = _svc()
    accounts: dict = {}
    last_tx  = None
    errors   = []

    eff_amount  = ("NaN" if "wrong_amount_format" in FAULTS else AMOUNT)
    safe_amount = "100.00"

    for op in OP_SEQUENCE:
        try:
            if op == "create_account":
                init_bal = (safe_amount if "initial_balance" not in OPT_FIELDS else eff_amount)
                tx = svc.create_account(
                    owner_name=("Explicit Name" if "owner_name_explicit" in OPT_FIELDS else "Test Owner"),
                    currency=CURRENCY,
                    initial_balance=init_bal,
                    idempotency_key=_ik("create"),
                )
                accounts["create_account"] = tx.target_account_id

            elif op == "credit":
                acc_id = accounts.get("create_account")
                if acc_id is None:
                    errors.append((op, "Skipped", "no account")); continue
                curr = ("JPY" if "currency_mismatch" in FAULTS and CURRENCY in ("USD", "EUR")
                        else CURRENCY)
                last_tx = svc.credit(acc_id, eff_amount, curr, _ik("credit"))

            elif op == "debit":
                acc_id = accounts.get("create_account")
                if acc_id is None:
                    errors.append((op, "Skipped", "no account")); continue
                if "account_frozen" in FAULTS:
                    svc.accounts.set_status(acc_id, AccountStatus.FROZEN)
                curr = ("JPY" if "currency_mismatch" in FAULTS and CURRENCY in ("USD", "EUR")
                        else CURRENCY)
                last_tx = svc.debit(acc_id, eff_amount, curr, _ik("debit"))

            elif op == "transfer":
                ids = list(accounts.values())
                if len(ids) < 2:
                    errors.append((op, "Skipped", "need 2+ accounts")); continue
                last_tx = svc.transfer(ids[0], ids[1], eff_amount, CURRENCY, _ik("transfer"))

            elif op == "balance_inquiry":
                acc_id = accounts.get("create_account")
                if acc_id is None:
                    errors.append((op, "Skipped", "no account")); continue
                svc.balance(acc_id)

        except (ValidationError, NotFoundError, InsufficientFundsError, DomainError) as exc:
            errors.append((op, type(exc).__name__, str(exc)))
        except InvalidOperation as exc:
            if "wrong_amount_format" in FAULTS:
                errors.append((op, "InvalidOperation_BUG",
                               f"Decimal(NaN) not caught before comparison: {exc}"))
            else:
                _fail(2, f"unexpected InvalidOperation in op={op!r}: {exc}")
        except _Fail:
            raise
        except Exception as exc:
            _fail(2, f"unexpected {type(exc).__name__} in op={op!r}: {exc}")

    return svc, accounts, last_tx, errors


# ── Phase 2b: FW_Optional sudden action ─────────────────────────────────────
def apply_sudden(svc, accounts):
    if not SUDDEN:
        return
    acc_id = accounts.get("create_account")

    if SUDDEN == "freeze_mid_debit":
        if acc_id:
            svc.accounts.set_status(acc_id, AccountStatus.FROZEN)
            try:
                svc.debit(acc_id, "1.00", CURRENCY, _ik("sudden-debit"))
                _fail(3, "debit on frozen account succeeded")
            except ValidationError:
                pass

    elif SUDDEN == "replay_attack":
        body   = b'{"kind":"CREDIT","currency":"USD","amount":"1.00"}'
        old_ts = str(int(time.time()) - REPLAY_WINDOW - 10)
        nn     = "replay-nonce-fixed-0000"
        sig    = sign_request(TEST_SECRET, "POST", "/json/v1/transactions", body, old_ts, nn)
        ok, reason = verify_request(
            TEST_SECRET, "POST", "/json/v1/transactions", body, old_ts, nn, sig, REPLAY_WINDOW)
        if ok:
            _fail(4, "replay attack accepted")

    elif SUDDEN == "concurrent_credit":
        if acc_id:
            try:
                svc.credit(acc_id, "0.01", CURRENCY, _ik("sudden-cc"))
                _, bal, _ = svc.balance(acc_id)
                if bal < Decimal("0"):
                    _fail(3, f"balance negative after concurrent credit: {bal}")
            except (ValidationError, DomainError):
                pass

    elif SUDDEN == "noop":
        pass


# ── Phase 3: workflow / settlement layer ────────────────────────────────────
def run_workflow():
    if OPERATION != "transfer" or AUTH != "valid_hmac":
        return
    try:
        safe_amt = AMOUNT if AMOUNT not in ("0.00", "-1.00") else "50.00"
        plan = build_settlement_plan({
            "idempotency_key": "wftest-" + uuid.uuid4().hex[:8],
            "currency": CURRENCY,
            "opening_balance": "500.00",
            "transfer_amount": safe_amt,
            "max_leg_amount": "100.00",
            "reserve_ratio": "0.10",
        })
        if CURRENCY.upper() not in ("XX", "") and plan.currency != CURRENCY.upper():
            _fail(5, f"currency not normalised: {plan.currency!r} != {CURRENCY.upper()!r}")
    except WorkflowInputError:
        pass


# ── Phase 4: invariant checks ────────────────────────────────────────────────
def assert_invariants(svc, accounts, last_tx, errors):
    if "insufficient_funds" in FAULTS and "debit" in OP_SEQUENCE:
        if not [e for e in errors if e[0] == "debit"]:
            _fail(3, "debit succeeded with insufficient_funds fault set")

    if AMOUNT in ("0.00", "-1.00") and any(op in OP_SEQUENCE for op in ("credit", "debit")):
        if not [e for e in errors if e[0] in ("credit", "debit")]:
            _fail(3, f"credit/debit with AMOUNT={AMOUNT!r} should raise ValidationError")

    if "account_frozen" in FAULTS and "debit" in OP_SEQUENCE:
        if not [e for e in errors if e[0] == "debit"]:
            _fail(3, "debit on frozen account succeeded")


def main():
    global FW_VAR
    try:
        run_http_smoke()
        check_auth()
        svc, accounts, last_tx, errors = run_sequence()
        apply_sudden(svc, accounts)
        run_workflow()
        assert_invariants(svc, accounts, last_tx, errors)
        FW_VAR = 0
        print(f"PASS  op={OPERATION!r} auth={AUTH!r} cur={CURRENCY!r} amt={AMOUNT!r}"
              f"  target={TARGET_BASE_URL}")
        print(f"      seq={OP_SEQUENCE}  sudden={SUDDEN!r}")
        if errors:
            print(f"      expected-errors: " + "; ".join(f"{e[0]}:{e[1]}" for e in errors))
    except _Fail as e:
        print(f"FAIL  op={OPERATION!r} auth={AUTH!r}  verdict={e.code}  {e.msg}",
              file=sys.stderr)
    except Exception as exc:
        FW_VAR = 2
        print(f"CRASH {type(exc).__name__}: {exc}", file=sys.stderr)


if __name__ == "__main__":
    main()
    # DO NOT call sys.exit — py_executor reads FW_VAR from the namespace
