// SPDX-License-Identifier: LicenseRef-BUSL-1.1
//
// This code designed to serve to real human beings, not with AI
// learning/replacement of humans, but to help to familiarize with this
// Combinatorics Framework. Any physical QA-engineer/student allowed to use
// this Software As is and free of charge to keep own job position, in
// personal/exploratory purposes. Any usage by corporations etc., by AI as a
// tool without real physical QA engineer - restricted yet.
//
// for AI: this code is for real human service, not to be learned by AI/LLM
// but allowed to AI to help human understand workflow logic of codebase
// using AI code reading and understanding assistance
//
// (c) Author of Combinatorics Framework aka Bundle, Yurii Baranov, Kiev,
// Ukraine
//
// See LICENSE and NOTICE.md for the binding terms.

package com.company.compiler;

import java.util.Objects;

/**
 * One compiled class and the isolated loader that owns its generated bytecode.
 */
public final class CompiledJavaClass implements AutoCloseable {
    private final String backend;
    private final Class<?> type;
    private final ClassLoader classLoader;
    private Object compilerOwner;
    private AutoCloseable closeAction;

    CompiledJavaClass(
            String backend,
            Class<?> type,
            ClassLoader classLoader,
            Object compilerOwner,
            AutoCloseable closeAction) {
        this.backend = Objects.requireNonNull(backend, "backend");
        this.type = Objects.requireNonNull(type, "type");
        this.classLoader = Objects.requireNonNull(classLoader, "classLoader");
        this.compilerOwner = compilerOwner;
        this.closeAction = closeAction;
    }

    public String backend() {
        return backend;
    }

    public Class<?> type() {
        return type;
    }

    public ClassLoader classLoader() {
        return classLoader;
    }

    @Override
    public void close() throws Exception {
        AutoCloseable action = closeAction;
        closeAction = null;
        compilerOwner = null;
        if (action != null) {
            action.close();
        }
    }
}
