package com.company.compiler;

import java.util.Objects;

/**
 * One compiled class and the isolated loader that owns its generated bytecode.
 */
public final class CompiledJavaClass implements AutoCloseable {
    private final String backend;
    private final Class<?> type;
    private final ClassLoader classLoader;
    private Object compilerOwner;
    private AutoCloseable closeAction;

    CompiledJavaClass(
            String backend,
            Class<?> type,
            ClassLoader classLoader,
            Object compilerOwner,
            AutoCloseable closeAction) {
        this.backend = Objects.requireNonNull(backend, "backend");
        this.type = Objects.requireNonNull(type, "type");
        this.classLoader = Objects.requireNonNull(classLoader, "classLoader");
        this.compilerOwner = compilerOwner;
        this.closeAction = closeAction;
    }

    public String backend() {
        return backend;
    }

    public Class<?> type() {
        return type;
    }

    public ClassLoader classLoader() {
        return classLoader;
    }

    @Override
    public void close() throws Exception {
        AutoCloseable action = closeAction;
        closeAction = null;
        compilerOwner = null;
        if (action != null) {
            action.close();
        }
    }
}
