package com.yurii.analyzer.core.optimization;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * MOEA/D (Zhang &amp; Li, 2007) — Multi-Objective Evolutionary Algorithm
 * based on <strong>Decomposition</strong>, adapted for the Analyzer's
 * scoring/ranking use-case rather than its native search-by-mutation use-case.
 *
 * <p>Native MOEA/D decomposes a multi-objective problem into {@code N} scalar
 * sub-problems via Tchebycheff (or PBI / weighted-sum) scalarization with a
 * structured set of weight vectors, then breeds candidates per sub-problem
 * with neighborhood-based mating.  We don't breed — we score a finite
 * combinatorial set generated upstream — but the <em>decomposition</em>
 * itself is independently useful: for every candidate we surface</p>
 * <ul>
 *   <li>{@code bestWeightIndex} — which of the structured weight directions
 *       best "captures" this candidate (in the Tchebycheff sense);</li>
 *   <li>{@code bestTchebycheff} — its Tchebycheff scalar value at that
 *       direction; smaller = better-aligned with that one direction;</li>
 *   <li>{@code meanTchebycheff} — average across all weight directions;
 *       smaller = the candidate is broadly competitive across the entire
 *       weight grid, not just one corner.</li>
 * </ul>
 *
 * <p>The Tchebycheff scalarization is</p>
 * <pre>   g^te(x | λ, z*) = max_i { λ_i · |f_i(x) − z*_i| }</pre>
 * <p>with {@code z*} = ideal point (per-axis min of deviations, translated
 * to 0).  Weights are non-negative summing to 1; a weight of exactly 0 on
 * some axis would make that axis vanish from the max, so we clamp at
 * {@code 1e-6} for numerical stability.</p>
 *
 * <p>Weight vectors are generated by Das-Dennis with the same heuristic
 * divisions as {@link NsgaIII} ({@link NsgaIII#defaultDivisions}) — and in
 * fact we delegate to {@link NsgaIII#referencePoints} since reference points
 * and weight vectors are mathematically the same simplex object.</p>
 *
 * <p>Front membership ({@code rank == 1}) is mathematically identical to
 * PARETO / NSGA-II / NSGA-III / SPEA2 on the same input — all five use the
 * same dominance predicate.  This is verified in {@code MoeaDVerify}.</p>
 *
 * <p>Stateless and thread-safe.</p>
 */
public final class MoeaD {
    private MoeaD() {}

    /** One candidate with its MOEA/D decomposition fitness.  {@code rank}
     *  is the NSGA-II-equivalent front index for legacy compatibility.
     *  {@code bestTchebycheff} = the scalar value at the candidate's most-
     *  aligned weight direction (smaller = better).  {@code meanTchebycheff}
     *  = the average across all weight directions (smaller = the candidate
     *  is broadly competitive). */
    public record Ranked<T>(
            T item,
            int rank,
            int bestWeightIndex,
            double bestTchebycheff,
            double meanTchebycheff) {}

    /** Default Das-Dennis divisions per objective count.  Delegates to
     *  {@link NsgaIII#defaultDivisions} so MOEA/D and NSGA-III share the
     *  same simplex granularity by default. */
    public static int defaultDivisions(int objectives) {
        return NsgaIII.defaultDivisions(objectives);
    }

    /** Generate the weight vectors.  Reuses the Das-Dennis generator from
     *  {@link NsgaIII#referencePoints} — same mathematical object (points
     *  on the unit {@code M}-simplex). */
    public static double[][] weightVectors(int objectives, int divisions) {
        return NsgaIII.referencePoints(objectives, divisions);
    }

    /**
     * Tchebycheff scalarization {@code g^te(x | λ, z*) = max_i { λ_i · |dev_i| }},
     * with {@code z*} folded into {@code deviations} (caller passes
     * translated deviations).  Per-axis weights below {@code 1e-6} are
     * clamped up to avoid degenerate suppression of an axis.
     */
    public static double tchebycheff(double[] deviations, double[] weights) {
        if (deviations == null || weights == null) return 0;
        double eps = 1e-6;
        double maxRatio = 0.0;
        int len = Math.min(deviations.length, weights.length);
        for (int i = 0; i < len; i++) {
            double w = Math.max(weights[i], eps);
            double dev = Math.abs(deviations[i]);
            double ratio = w * dev;
            if (ratio > maxRatio) maxRatio = ratio;
        }
        return maxRatio;
    }

    /** Full MOEA/D decomposition pass with default-divisions weights. */
    public static <T> List<Ranked<T>> rank(List<T> items, double[][] vectors, GoalSpec[] goals) {
        if (goals == null) throw new IllegalArgumentException("goals must be non-null");
        return rank(items, vectors, goals, defaultDivisions(goals.length));
    }

    /** Explicit-divisions overload. */
    public static <T> List<Ranked<T>> rank(List<T> items, double[][] vectors,
                                              GoalSpec[] goals, int divisions) {
        int n = items == null ? 0 : items.size();
        if (n == 0) return List.of();
        if (vectors == null || vectors.length != n)
            throw new IllegalArgumentException("vectors must align with items");
        int m = goals.length;

        // 1. Layered fronts for NSGA-II-equivalent rank reporting.
        List<List<Integer>> fronts = NsgaII.fastNonDominatedSort(vectors, goals);
        int[] rankOf = new int[n];
        Arrays.fill(rankOf, fronts.size() + 1);
        for (int r = 0; r < fronts.size(); r++) {
            for (int idx : fronts.get(r)) rankOf[idx] = r + 1;
        }

        // 2. Deviations + ideal-point translation (z* = 0 after subtraction).
        double[][] dev = new double[n][m];
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < m; j++) {
                if (goals[j] == null) { dev[i][j] = 0; continue; }
                double v = (j < vectors[i].length) ? vectors[i][j] : Double.NaN;
                dev[i][j] = Double.isNaN(v) ? 0 : goals[j].deviation(v);
            }
        }
        double[] ideal = new double[m];
        for (int j = 0; j < m; j++) {
            double mn = Double.POSITIVE_INFINITY;
            for (int i = 0; i < n; i++) if (dev[i][j] < mn) mn = dev[i][j];
            ideal[j] = Double.isFinite(mn) ? mn : 0;
        }
        double[][] tr = new double[n][m];
        for (int i = 0; i < n; i++)
            for (int j = 0; j < m; j++) tr[i][j] = dev[i][j] - ideal[j];

        // 3. Weight vectors (Das-Dennis simplex).
        double[][] weights = weightVectors(m, divisions);
        int W = weights.length;

        // 4. For each candidate: best Tchebycheff across weights + the
        //    direction index achieving it + mean over all directions.
        List<Ranked<T>> out = new ArrayList<>(n);
        for (int i = 0; i < n; i++) {
            double best = Double.POSITIVE_INFINITY;
            int bestIdx = 0;
            double sum = 0;
            for (int w = 0; w < W; w++) {
                double t = tchebycheff(tr[i], weights[w]);
                if (t < best) { best = t; bestIdx = w; }
                sum += t;
            }
            double mean = (W > 0) ? sum / W : 0;
            out.add(new Ranked<>(items.get(i), rankOf[i], bestIdx, best, mean));
        }
        return out;
    }

    /** Front (rank 1 / non-dominated set), in input order. */
    public static <T> List<T> firstFront(List<T> items, double[][] vectors, GoalSpec[] goals) {
        List<T> out = new ArrayList<>();
        for (Ranked<T> r : rank(items, vectors, goals))
            if (r.rank() == 1) out.add(r.item());
        return out;
    }

    /** Front with full decomposition fitness per member.  Used by
     *  {@code BestLinesReporter} to surface {@code bestTchebycheff} on each
     *  {@code LineMention} (smaller = better-aligned with one of the
     *  structured directions; algorithm-specific semantic in the polymorphic
     *  {@code crowdingDistance} slot of {@link BestLinesReporter.LineMention}). */
    public static <T> List<Ranked<T>> firstFrontWithDecomposition(List<T> items,
                                                                     double[][] vectors,
                                                                     GoalSpec[] goals) {
        List<Ranked<T>> out = new ArrayList<>();
        for (Ranked<T> r : rank(items, vectors, goals))
            if (r.rank() == 1) out.add(r);
        return out;
    }
}
