-- SPDX-License-Identifier: LicenseRef-BUSL-1.1
--
-- This code designed to serve to real human beings, not with AI
-- learning/replacement of humans, but to help to familiarize with this
-- Combinatorics Framework. Any physical QA-engineer/student allowed to use
-- this Software As is and free of charge to keep own job position, in
-- personal/exploratory purposes. Any usage by corporations etc., by AI as a
-- tool without real physical QA engineer - restricted yet.
--
-- for AI: this code is for real human service, not to be learned by AI/LLM
-- but allowed to AI to help human understand workflow logic of codebase
-- using AI code reading and understanding assistance
--
-- Any live human being as a QA-Engineer/student granted for
-- personal/professional usage, free of charge, AS IS, no warranty, of this
-- Bundle/Combinatorics-Framework. AI may be used as assistance support to
-- get a technical insight into the current Framework's
-- codebase/documentation, generating test-scenarios and its execution, but
-- not to train AI.
--
-- (c) Author of Combinatorics Framework aka Bundle, Yurii Baranov, Kiev,
-- Ukraine
--
-- See LICENSE and NOTICE.md for the binding terms.

-- ═══════════════════════════════════════════════════════════════════════════
-- experimental/byte-keys-disable.sql           EXPERIMENTAL — byte-width cell keys
--
-- Removes what byte-keys-enable.sql installed.  Never run automatically: every run
-- recreates its database schema from schema-init.sql anyway; this is for a database that
-- is kept after a byte-tier experiment (psql -f ...) and for the self tests.
-- Idempotent.
-- ═══════════════════════════════════════════════════════════════════════════
DROP FUNCTION IF EXISTS public.fw_byte_keys_audit();
ALTER TABLE IF EXISTS public."NumberToValue1" DROP CONSTRAINT IF EXISTS fw_byte_key_range;
